{% set data = load_setup_py_data() %}

package:
  name: pcdsdaq
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - python {{PY_VER}}*,>=3
    - setuptools

  run:
    - python {{PY_VER}}*,>=3
    - ophyd >=1.1.0
    - bluesky >=1.2.0
    - toolz
    - matplotlib <3

test:
  imports:
    - pcdsdaq

about:
  home: https://github.com/pcdshub/pcdsdaq
  license: SLAC Open License
  summary: DAQ Control Interface
