#!/bin/bash
# This script generates a fresh linker script to create links to the
# pydaq.so and pycdb.so python modules. This is done because the modules
# must be renamed from pydaq.so.3, etc. to be importable.
set -e
DAQ_ROOT="/reg/g/pcds/dist/pds"
LINKER="linker"
for hutch in current amo sxr xpp xcs mfx cxi mec
do
  for os in x86_64-linux x86_64-rhel7
  do
    my_dir="links/${hutch}/${os}"
    echo "mkdir -p \"${my_dir}\"" >> "${LINKER}"
    for module in pydaq pycdb
    do
      suffix="current/build/pdsapp/lib/${os}/${module}.so.3"
      link_name="${my_dir}/${module}.so"
      if [ "${hutch}" = "current" ]; then
        echo "ln -s \"${DAQ_ROOT}/${suffix}\" \"${link_name}\"" >> "${LINKER}"
      else
        echo "ln -s \"${DAQ_ROOT}/${hutch}/${suffix}\" \"${link_name}\"" >> "${LINKER}"
      fi
    done
  done
done
chmod a+x "${LINKER}"
